# Site settings
title: "#TrainTheSwamp"
description: "Report Cards for Congress"
baseurl: ""
url: "http://traintheswamp.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Links
links:
  - title: "order"
    url: /order
  - title: "about"
    url: /about
  - title: "faq"
    url: /faq
  # - title: "twitter"
  #   url: http://twitter.com/traintheswamp
